application: calvaryslz-lutheran
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/login_required
  script: auth/login.py

- url: /auth
  static_dir: auth/resources

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /blog-test
  static_files: html/blog.html
  upload: html/blog.html

- url: /school.*
  script: school/urls.py
  login: required

- url: /church.*
  script: church/urls.py

- url: /data/.*
  script: plugins/urls.py

- url: /css
  static_dir: stylesheets

- url: /js
  static_dir: javascript

- url: /media
  static_dir: media

